name: Fetch Data, Build HTML & Deploy

on:
#  schedule:
#    - cron: '0 5 * * *' # Runs at 05:00 UTC every day
  # You can also trigger this workflow manually
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Fetch data and build HTML
      run: |
        make all

    - name: Deploy build to gh pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: _build